create schema if not exists merchants;

comment on schema merchants is 'tracks payment activity of merchant customers';

create table if not exists merchants.dim_payment_method
(
	payment_method_pk int generated by default as identity ( 1,1 ) not null encode az64
		constraint payment_method_pk
			primary key,
	payment_method_name varchar(25) not null
		constraint dim_payment_method_payment_method_name_key
			unique,
	sys_loading_date timestamp default ('now'::text)::timestamp with time zone not null encode az64
)
diststyle all;

create table if not exists merchants.dim_payment_status
(
	payment_status_pk int generated by default as identity ( 1,1 ) not null encode runlength
		constraint payment_status_pk
			primary key,
	payment_status_name varchar(25) not null
		constraint dim_payment_status_payment_status_name_key
			unique,
	sys_loading_date timestamp default ('now'::text)::timestamp with time zone not null encode az64
)
diststyle all;

create table if not exists merchants.dim_merchant
(
	merchant_pk int  generated by default as identity ( 1,1 ) not null encode runlength distkey
		constraint merchant_pk
			primary key,
	merchant_id varchar(100) not null,
	merchant_name varchar(50),
	address varchar(100),
	phone_number varchar(30),
	email varchar(200),
	from_date date not null encode az64,
	to_date date not null encode az64,
	date_created timestamp default ('now'::text)::timestamp with time zone not null encode az64,
	data_modified timestamp default ('now'::text)::timestamp with time zone not null encode az64
)
diststyle key
interleaved sortkey(merchant_id, merchant_name);

create table if not exists merchants.fact_payments
(
	payment_id bigint not null encode runlength
		constraint payment_pk
			primary key,
	merchant_fk bigint not null encode az64 distkey
		constraint merchant_fk
			references merchants.dim_merchant,
	payment_method_fk bigint not null
		constraint payment_method_fk
			references merchants.dim_payment_method,
	payment_status_fk bigint not null
		constraint payment_status_fk
			references merchants.dim_payment_status,
	payment_date date not null,
	payment_amount numeric(10,2) not null encode az64,
	ingestion_date date default ('now'::text)::date not null encode az64,
	sys_loading_date timestamp default ('now'::text)::timestamp with time zone not null encode az64
)
diststyle key
sortkey(payment_date, payment_method_fk, payment_status_fk);

