create schema if not exists mrr_merchants;

comment on schema mrr_merchants is 'contains source data from s3';

create table if not exists mrr_merchants.merchants
(
	merchant_id varchar(100),
	merchant_name varchar(50),
	address varchar(100),
	phone_number varchar(30),
	email varchar(200),
	ingestion_date date encode az64
)  sortkey  (merchant_id);

create table if not exists mrr_merchants.payments
(
	payment_id bigint not null encode runlength
		constraint payments_pk
			primary key,
	merchant_id varchar(100),
	payment_amount numeric(10,2) encode az64,
	payment_method varchar(20),
	status varchar(20),
	payment_date date encode az64,
	customer_id varchar(100),
	ingestion_date date encode az64
) diststyle key distkey (merchant_id)
sortkey(payment_date);

create table if not exists mrr_merchants.manage_sources
(
	table_id int generated by default as identity ( 1,1 ) not null
		constraint manage_sources_pk
			primary key,
	table_name varchar(200) not null,
	from_ts timestamp not null,
	to_ts timestamp not null,
	sys_loading_date timestamp default current_timestamp not null
);

insert into mrr_merchants.manage_sources(table_name, from_ts, to_ts)
select 'merchants.payments','20000101','20000101'
where not exists(select 1 from mrr_merchants.manage_sources
    where table_name='merchants.payments');